
  dbrps:
   - {db: "test", rp: "dia"}
  template-id: "basic_template"
  vars: {
    "measurement": {"type" : "string", "value" : "system" },
    "where_filter": {"type": "lambda", "value": "\"host\" == 'host2'"},
    "field": {"type" : "string", "value" : "load15" },
    "warn": {"type" : "lambda", "value" : "\"mean\" < '1.499896414'" },
    "crit": {"type" : "lambda", "value" : "\"mean\" < '0.67072799'" },
    "warnin": {"type" : "string", "value" : "20" },
    "criti": {"type" : "string", "value" : "10" },
    "window": {"type" : "duration", "value" : "30m" },
    "slack_channel": {"type" : "string", "value" : "#test" }
  }

